### ISSUE TITLE
You have requested a non-existent parameter "deployment_type".

### ISSUE THREAD

**Issue by Scarbous** [marellocommerce/marello-application#14]
When I follow the setup steps i get the following error on "bin/console oro:install --env prod"

```
In DefinitionErrorExceptionPass.php line 54:

  You have requested a non-existent parameter "deployment_type".
```

**Comment by pschoenmakers** [comment]
Yes, getting this error right now as well.

**Comment by pschoenmakers** [comment]
@Scarbous I see you managed to get the installatation beyond this error in #15  
Can you share what you have done?

**Comment by Scarbous** [comment]
@pschoenmakers I set the missing config to parameters.yml
```yml
# This file is auto-generated during the composer install
parameters:
    .....
    deployment_type: ~
```

But its gone every time when I run `composer install`.
